### PR TITLE
proper format the library

### PR DESCRIPTION
**Pull request by long1eu**

### CODE REVIEW

**Comment by long1eu** [comment]
fallow https://www.dartlang.org/guides/libraries/create-library-packages and dart naming conventions

**Comment by wendux** [comment]
Good job! But [the group test failed in travis-ci]( https://travis-ci.org/flutterchina/cookie_jar/builds/382509687?utm_source=github_status&utm_medium=notification) with your change.

**Comment by long1eu** [comment]
I'll take a look.

**Comment by long1eu** [comment]
this is strange because they work on me

**Comment by long1eu** [comment]
did you tried it with dart 2.0?

**Comment by long1eu** [comment]
It looks like the tests are not executed by travis. Can you look into that?

**Comment by wendux** [comment]
Changing dart-vm version to latest dev version, it worked.

**Comment by long1eu** [comment]
awesome :D

**Pull request merged**
